name: flutter_pdf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pdf:
  #printing:
  flutter_html_to_pdf: ^0.7.0
  path_provider:
  flutter_full_pdf_viewer_null_safe:
  google_fonts: ^3.0.1
  syncfusion_flutter_pdf: ^20.2.44
  open_file: ^3.2.1
  flutter_widget_from_html: ^0.8.5
  screenshot: ^1.2.3
  pdfx: ^2.2.0
  universal_platform: ^1.0.0+1
  internet_file: ^1.2.0
  syncfusion_flutter_pdfviewer: ^20.1.58-beta
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/fonts/
     - assets/pdf/

  fonts:
    - family: Nikosh
      fonts:
        - asset: assets/fonts/Nikosh.ttf
    - family: Kalpurush
      fonts:
        - asset: assets/fonts/kalpurush_ANSI.ttf
        - asset: assets/fonts/kalpurush.ttf.
    - family: Shurjo
      fonts:
        - asset: assets/fonts/Shurjo_UNICODE_Regular.ttf
        - asset: assets/fonts/Shurjo_UNICODE_Bold.ttf
          weight: 700
